### PR TITLE
Set cookie path to URL of homepage

### PR DESCRIPTION
**Pull request by mgax**
Fixes https://github.com/wagtail-nest/wagtail-ab-testing/issues/46

### CODE REVIEW

**Review by tomusher — APPROVED** [review]
Looks good to me. Are there any cases you can think of where the path of a root page is not `/`, or is this for future proofing?

**Comment by mgax** [comment]
> Are there any cases you can think of where the path of a root page is not `/`, or is this for future proofing?

Future-proofing, in case somebody hosts a couple of Wagtail websites on the same domain. Though I'm wondering if the approach is right, because it introduces 2 database queries for each page load. Perhaps a better approach is to pass a `site` argument to the inclusion tag, and only if that's present, compute the homepage's URL, otherwise just use `/`?

**Review by tomusher — APPROVED** [review]
Great, that change makes sense to me!

**Review by Stormheg — APPROVED** [review]
Thank you! Just setting this to the root path sounds fine to me.

**Pull request merged**
